sudo: false
language: node_js
node_js:
  - '10'
  - '11'
# keep the npm cache to speed up installs
cache:
  directories:
    - node_modules/
branches:
  only:
    - master
    - dev
after_success:
  - codecov
  - yarn run build
